// frontend/src/components/Graph.vue
<script setup>
import axios from 'axios'
import Chart from 'chart.js/auto'
import { useRoute } from 'vue-router'
import {watchEffect, onMounted } from 'vue'

      let Temp = []
      let Hum = []
      let labels = []
      const route = useRoute()

      const config = {
          type: 'line',
          data: {
            labels: Array,
            datasets: [{
              label: 'temperature',
              backgroundColors: '#B4BEFE',
              borderColor: '#B4BEFE',
              borderWidth: 2,
              data: Array,
              tension: 0.3
            },
            {
              label: 'Humidity',
              backgroundColors: '#89B4FA',
              borderColor: '#89B4FA',
              borderWidth: 2,
              data: Array,
              tension: 0.3
            }]
          },
        
        }

      watchEffect(() => {
        setInterval(async () => {
          const res = await axios.get(`http://localhost:5000/graphreport/${route.params.id}`)
          const reports = await res.data.rows
          reports.forEach(report => {
          let date = new Date(Number(report.mesured_at))
          const dateFormatted = `${date.getFullYear()} - ${(date.getMonth() + 1).toString().padStart(2, '0')} - ${date.getDate().toString().padStart(2, '0')} | ${date.getHours()}h${date.getMinutes() <= 9 ? '!' + date.getMinutes() : '0' + date.getMinutes()}`;
          Temp.push(report.temperature)
          Hum.push(report.humidity)
          labels.push(dateFormatted)
          })
			}, 300000);
      }),

      onMounted(async () => {
        const res = await axios.get(`http://localhost:5000/graphreport/${route.params.id}`)
        const reports = await res.data.rows
        reports.forEach(report => {
        let date = new Date(Number(report.mesured_at))
        const dateFormatted = `${date.getFullYear()} - ${(date.getMonth() + 1).toString().padStart(2, '0')} - ${date.getDate().toString().padStart(2, '0')} | ${date.getHours()}h${date.getMinutes() <= 9 ? '0' + date.getMinutes() : + date.getMinutes()}`;
        Temp.push(report.temperature)
        Hum.push(report.humidity)
        labels.push(dateFormatted)
      });


      Temp = Temp.slice(-50).reverse()
      Hum = Hum.slice(-50).reverse()
      labels = labels.slice(-50).reverse()
      config.data.datasets[0].data = Temp
      config.data.datasets[1].data = Hum
      config.data.labels = labels

      const myChart = new Chart(
      document.getElementById('myChart'),
      config
      )})
</script>


<template>
    <canvas id="myChart"></canvas>
</template>

// frontend-react/src/components/Graph.jsx
import React from 'react';
import {Chart as ChartJS,CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend,} from 'chart.js';
import { Line } from 'react-chartjs-2';
import axios from 'axios'
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { URL_API } from '../../config'

ChartJS.register(CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend,);

export const options = {
    responsive: true,
    maintainAspectRatio: false,
    scales: {
        y: {beginAtZero: true},
        x: {
            display: true,
            position: "top",
        },
    },
};

export function Graph() {

    const { id } = useParams()
    const [reports, setReports] = useState([])

    useEffect(() => {
        axios.get(`http://${URL_API}/graphreport/${id}`)
        .then((data) => { setReports(data.data.rows)})
        .catch((err) => { console.log(err) })
    setInterval(() => {
    let mounted = true
    axios.get(`http://${URL_API}/graphreport/${id}`)
        .then((data) => { if(mounted) { setReports(data.data.rows) } })
        .catch((err) => { console.log(err) })
        return () => mounted = false;
    }, 300000)
    }, [id])

    let dateArray = [];
    let TempArray = [];
    let HumArray = [];
    reports.map((report) => {
        let date = new Date(Number(report.mesured_at)).toLocaleString();
        dateArray.push(date);
        TempArray.push(report.temperature);
        HumArray.push(report.humidity);
    })
    const data = {
        labels : [...dateArray.reverse()],
        datasets: [
        {
            label: 'Temperature',
            data: [...TempArray.reverse()],
            backgroundColors: '#B4BEFE',
            borderColor: '#B4BEFE',
            tension: 0.3
        },
        {
            label: 'Humidity',
            data: [...HumArray.reverse()],
            backgroundColors: '#89B4FA',
            borderColor: '#89B4FA',
            tension: 0.3
        },
        ],
  };

    return (
        <Line options={options} data={data} width={"100%"}/>
    )
  }
